### ISSUE TITLE
[ValidationError] invalid characters in URL: `[` `]`

### ISSUE THREAD

**Issue by mLuca** [CycloneDX/cyclonedx-webpack-plugin#1239]
## To Reproduce

1. How was _@cyclonedx/webpack-plugin_  called?
See attached webpack.config.js. Was called as described in the official npm package site.

2. What kind of evidence was processed?
See attached package.json i.e. package-lock.json

3. Error report:
```
### Output Start ###
npm run build

> getk@0.1.0 build
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

Failed to generate valid BOM "bom/bom.xml"
Please report the issue and provide the npm lock file of the current project to:
https://github.com/CycloneDX/cyclonedx-webpack-plugin/issues/new?template=ValidationError-report.md&labels=ValidationError&title=%5BValidationError%5D
### Output End ###
```

5. Expected result:
See attached bom-folder. 
Created by adding "validateResults: false" to the options.

## Environment

- _@cyclonedx/webpack-plugin_ version: v3.8.2
- webpack version: webpack@5.77.0
- Node version: v18.17.0
- OS: debian 11
 
## Additional context

[artifacts.zip](https://github.com/CycloneDX/cyclonedx-webpack-plugin/files/13504060/artifacts.zip)

**Comment by jkowalleck** [comment]
thanks for the report. i will have a look.

**Comment by jkowalleck** [comment]
as of https://github.com/CycloneDX/cyclonedx-webpack-plugin/issues/1239#issuecomment-1836447296
the issue is caused by `jss-plugin-camel-case` -- https://github.com/cssinjs/jss/tree/master/packages/jss-plugin-camel-case

the "bug URL" `https://github.com/cssinjs/jss/issues/new?title=[jss-plugin-camel-case]` 
is actually invalid.
characters `[]` are invalid characters to URL standards. they must be url encoded `%5B%5D`.

possible fix can be done in https://github.com/CycloneDX/cyclonedx-javascript-library
would not be the first time to fix this ...
see <https://github.com/search?q=repo%3ACycloneDX%2Fcyclonedx-php-library+%255B&type=code>

**Comment by jkowalleck** [comment]
closed, since the underlying https://github.com/CycloneDX/cyclonedx-javascript-library/issues/992 was closed and a fix was published.
